# Generated by Django 4.2.14 on 2024-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='softskill',
            name='logo',
            field=models.ImageField(default='https://via.placeholder.com/128', upload_to='skills/logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='logo',
            field=models.ImageField(default='https://via.placeholder.com/128', upload_to='skills/logos/'),
            preserve_default=False,
        ),
    ]
