# Generated by Django 4.2.14 on 2024-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_softskill_logo_technicalskill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskill',
            name='logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='logo',
            field=models.CharField(max_length=500),
        ),
    ]
