# Generated by Django 4.2.14 on 2024-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_softskill_logo_alter_technicalskill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetDEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('outil_utilise', models.CharField(max_length=100)),
                ('lien_projet', models.URLField()),
                ('lien_portfolio', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('outil_utilise', models.CharField(max_length=100)),
                ('lien_projet', models.URLField()),
                ('lien_portfolio', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('outil_utilise', models.CharField(max_length=100)),
                ('lien_projet', models.URLField()),
                ('lien_portfolio', models.URLField()),
            ],
        ),
    ]
