# Generated by Django 4.2.14 on 2024-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projetdl_algorithmes_utilises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetdev',
            name='outil_utilise',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projetdl',
            name='outil_utilise',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projetml',
            name='outil_utilise',
            field=models.CharField(max_length=1000),
        ),
    ]
