# Generated by Django 4.2.14 on 2024-07-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projetdev_pdf_projetdl_pdf_projetml_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetdev',
            old_name='lien_portfolio',
            new_name='lien_github',
        ),
        migrations.RenameField(
            model_name='projetdl',
            old_name='lien_portfolio',
            new_name='lien_github',
        ),
        migrations.RenameField(
            model_name='projetml',
            old_name='lien_portfolio',
            new_name='lien_github',
        ),
        migrations.RemoveField(
            model_name='projetdev',
            name='pdf',
        ),
    ]
